"""Agent Security v4.2 — P0 异常规则.

ANOM-SECRET-IN-PROMPT
ANOM-DANGEROUS-SHELL
ANOM-SENSITIVE-READ-THEN-NETWORK
ANOM-MCP-REPEATED-FAILURE
ANOM-TOOL-LOOP
ANOM-CROSS-WORKSPACE-PATH
ANOM-APPROVAL-MISMATCH
ANOM-RAW-CAPTURE-ENABLED
"""
